@startuml dte-leitor
skinparam style strictuml

[*] --> NaoCadastrado

state NaoCadastrado {
}

NaoCadastrado --> Cadastrado : cadastrar()

state Cadastrado {
    [*] --> Deslogado
    Deslogado --> Logado : login() [credenciais válidas]
    Logado --> Deslogado : logout()
}

state Logado {
    [*] --> Ocioso

    Ocioso --> GerenciandoEstante : criarEstante()

    state GerenciandoEstante {
        [*] --> EstanteAtiva

        EstanteAtiva --> EstanteAtiva : adicionarLivro()\nremoverLivro()
        EstanteAtiva --> CriandoSubEstante : criarSubEstante()\n[EstanteComum]
        CriandoSubEstante --> EstanteAtiva : sub-estante criada

        EstanteAtiva --> [*] : removerEstante()
    }

    GerenciandoEstante --> Ocioso : estante fechada

    Ocioso --> Comprando : comprarLivro()

    state Comprando {
        [*] --> SelecionandoLivro
        SelecionandoLivro --> ConfirmandoCompra : selecionar livro
        ConfirmandoCompra --> CompraAprovada : pagamento aprovado
        ConfirmandoCompra --> CompraRecusada : pagamento recusado
        CompraAprovada --> [*]
        CompraRecusada --> [*]
    }
    Comprando --> Ocioso : compra finalizada\nou cancelada

    Ocioso --> Lendo : lerLivro()\n[leitor EPUB incializado]

    state Lendo {
        [*] --> NaPaginaAtual
        NaPaginaAtual --> NaPaginaAtual : avancarPagina()\n[not ultima]
        NaPaginaAtual --> NaPaginaAtual : voltarPagina()\n[paginaAtual > 1]
        NaPaginaAtual --> MarcandoPaginaAtual : PaginaLeitorEPUB.marcar()
        MarcandoPaginaAtual --> NaPaginaAtual : PaginaLeitorEPUB.desmarcar()
        MarcandoPaginaAtual --> MarcandoPaginaAtual : avancarPagina()\nvoltarPagina()

        NaPaginaAtual --> LivroFinalizado : avancarPagina()\n[ultima == true]
        MarcandoPaginaAtual --> LivroFinalizado : avancarPagina()\n[ultima == true]

        LivroFinalizado --> [*]
    }
    
    Lendo --> Ocioso : fecharLivro()\n[leitorEPUB.fecharLivro()]
    Lendo --> AvaliacaoPendente : fecharLivro()\n[finalizado == true]

    AvaliacaoPendente --> Avaliando : avaliarLivro()\n[IAvaliador]
    AvaliacaoPendente --> Ocioso : ignorar avaliação

    state Avaliando {
        [*] --> RascunhoAvaliacao
        RascunhoAvaliacao --> AvaliacaoPublicada : confirmar\n(estrelas + texto)
        AvaliacaoPublicada --> AvaliacaoPublicada : editarAvaliacao()\n[IAvaliador]
        AvaliacaoPublicada --> [*] : excluirAvalicao()\n[IAvaliador]
    }

    Avaliando --> Ocioso : avaliação concluída\nou descartada

    Ocioso --> Comentando : comentarAvaliacao()\n[IComentador]

    state Comentando {
        [*] --> RascunhoComentario
        RascunhoComentario --> ComentarioPublicado : confirmar comentário
        ComentarioPublicado : editarComentario()\n[IComentador]
        ComentarioPublicado --> [*] : excluirComentario()\n[IComentador]
    }
    
    Comentando --> Ocioso : comentário concluído \nou descartado
}
@enduml