@startuml dte-leitor-epub

[*] --> LeitorEPUBIniciado

LeitorEPUBIniciado --> AvancandoPagina : avancarPagina()
AvancandoPagina --> AvancandoPagina : marcarPagina()\navancandoPagina()\n[paginaAtual < ultimaPagina]

AvancandoPagina --> VoltandoPagina : voltarPagina()\n[paginaAtual > 1]
VoltandoPagina --> VoltandoPagina : marcarPagina()\nvoltarPagina()[paginaAtual > 1]
VoltandoPagina --> AvancandoPagina : avancarPagina()

AvancandoPagina --> LeitorEPUBFinalizado : avancarPagina()\n[paginaAtual == ultimaPagina]

LeitorEPUBFinalizado --> [*]

@enduml