@startuml dc-analisar_livros
autonumber
skinparam style strictuml

actor UsuarioEditorial as "UsuárioEditorial"
participant Client           as "Aplicação Cliente"
participant ServiceDashboard as "Serviço de Dashboard"
database    BD               as "Banco de Dados"

UsuarioEditorial -> Client : acessa o Dashboard\ne seleciona "Livros"

Client -> ServiceDashboard : GET /dashboard/livros\n(usuarioEditorialId)

ServiceDashboard -> BD : SELECT id, titulo, mediaAvaliacoes,\ntotalVendas, arquivado\nFROM livro WHERE publicadorId = {id}\nORDER BY totalVendas DESC
BD --> ServiceDashboard : lista de livros com métricas

ServiceDashboard --> Client : 200 OK — lista de livros com\ntotalVendas e \nmediaAvaliacoes

Client --> UsuarioEditorial : exibe painel com tabela de livros\ne métricas de desempenho (vendas e media de avaliações)

UsuarioEditorial -> Client : clica em um livro
Client -> ServiceDashboard : GET /dashboard/livros/{livroId}\n(usuarioEditorialId)
ServiceDashboard -> BD : SELECT métricas detalhadas\nWHERE livroId = {id}
BD --> ServiceDashboard : métricas detalhadas do livro
ServiceDashboard --> Client : 200 OK — métricas detalhadas
Client --> UsuarioEditorial : exibe painel detalhado do livro


@enduml
