@startuml diagrama-casos-uso
actor Usuario
actor UsuarioEditorial
actor Leitor
actor Autor
actor Editora

Leitor --|> Usuario
Autor --|> UsuarioEditorial
Editora --|> UsuarioEditorial
UsuarioEditorial --|> Usuario

' Feature - CRUD de Usuários

usecase "Fazer cadastro" as cadastrar
usecase "Fazer login" as login

Usuario --> cadastrar
Usuario --> login

' Feature - CRUD de Livros

usecase "Cadastrar livros" as cadastrar_livros
usecase "Fazer upload EPUB" as upload_epub
usecase "Autenticar" as autenticar
usecase "Editar livros" as editar_livros
usecase "Arquivar livros" as arquivar_livros
usecase "Remover livros" as remover_livros

UsuarioEditorial --> cadastrar_livros
cadastrar_livros ..> upload_epub : <<include>>
cadastrar_livros ..> autenticar : <<include>>
UsuarioEditorial --> editar_livros
UsuarioEditorial --> arquivar_livros

arquivar_livros ..> remover_livros : <<extend>>

' Feature - Catálogo de Livros

usecase "Comprar livros" as comprar_livros
usecase "Selecionar método pagamento" as selecionar_metodo_pgto
usecase "Receber por livro" as receber_por_livro
usecase "Aplicar cupom de desconto" as aplicar_cupom
usecase "Filtrar livros" as filtrar_livros
usecase "Pesquisar livros" as pesquisar_livros
usecase "Aplicar Filtros" as aplicar_filtros

Leitor --> comprar_livros
UsuarioEditorial --> receber_por_livro

Leitor --> filtrar_livros
Leitor --> pesquisar_livros

pesquisar_livros ..> aplicar_filtros : <<extend>>

comprar_livros ..> selecionar_metodo_pgto : <<include>>
comprar_livros ..> aplicar_cupom : <<extend>>

' Feature - Emprésitmo de Livros

usecase "Pegar livro emprestado" as pegar_livro_emprestado
usecase "Devolver livro" as devolver_livro
usecase "Receber notificação" as receber_notificacao
usecase "Aplicar cupom de extensão de prazo" as aplicar_cupom_prazo

Leitor --> pegar_livro_emprestado

pegar_livro_emprestado ..> devolver_livro : <<include>>
pegar_livro_emprestado ..> aplicar_cupom_prazo : <<extend>>

devolver_livro ..> receber_notificacao : <<include>>

' Feature - Leitura de Livros

usecase "Ler livros" as ler_livros
usecase "Marcar página" as marcar_pagina
usecase "Alterar modo de leitura" as alterar_modo_leitura

Leitor --> ler_livros

ler_livros ..> marcar_pagina : <<extend>>
ler_livros ..> alterar_modo_leitura : <<extend>>

' Feature - Avaliação de Livros

usecase "Avaliar livros" as avaliar_livros
usecase "Adicionar comentário" as adicionar_comentario
usecase "Comentar em avaliações" as comentar_avaliacoes
usecase "Responder avaliações de leitores" as responder_avaliacoes 

Leitor --> avaliar_livros
Leitor --> comentar_avaliacoes

UsuarioEditorial --> responder_avaliacoes

avaliar_livros ..> adicionar_comentario : <<extend>>

' Feature - Organização de Livros

actor "Subsistema de Bibliotecas" as SubsistemaBiblioteca

usecase "Criar biblioteca" as criar_biblioteca
usecase "Inserir na estante de adquiridos" as inserir_estante_adquiridos
usecase "Remover empréstimo de adquiridos" as remover_emprestimo_adquiridos
usecase "Inserir na estante de avaliados" as inserir_estante_avaliados
usecase "Inserir no histórico de livros" as inserir_historico_livros

SubsistemaBiblioteca --> criar_biblioteca
SubsistemaBiblioteca --> inserir_estante_adquiridos
inserir_estante_adquiridos ..> remover_emprestimo_adquiridos: <<extend>>
SubsistemaBiblioteca --> inserir_estante_avaliados
SubsistemaBiblioteca --> inserir_historico_livros


@enduml