@startuml diagrama-casos-uso

actor Usuario
actor UsuarioEditorial
actor Leitor
actor Autor
actor Editora

Leitor --|> Usuario
Autor --|> UsuarioEditorial
Editora --|> UsuarioEditorial
UsuarioEditorial --|> Usuario

' Feature - CRUD de Usuários

usecase "UC01\nFazer cadastro" as cadastrar
usecase "UC02\nFazer login" as login

Usuario --> cadastrar
Usuario --> login

' Feature - CRUD de Livros

usecase "UC03\nCadastrar livros" as cadastrar_livros
usecase "UC04\nFazer upload EPUB" as upload_epub
usecase "UC05\nAutenticar" as autenticar
usecase "UC06\nEditar livros" as editar_livros
usecase "UC07\nArquivar livros" as arquivar_livros
usecase "UC08\nRemover livros" as remover_livros

UsuarioEditorial --> cadastrar_livros
cadastrar_livros ..> upload_epub : <<include>>
cadastrar_livros ..> autenticar : <<include>>
UsuarioEditorial --> editar_livros
UsuarioEditorial --> arquivar_livros

arquivar_livros ..> remover_livros : <<extend>>


' Feature - Catálogo de Livros

usecase "UC09\nComprar livros" as comprar_livros
usecase "UC10\nSelecionar método pagamento" as selecionar_metodo_pgto
usecase "UC11\nReceber por livro" as receber_por_livro
usecase "UC12\nFiltrar livros" as filtrar_livros
usecase "UC13\nPesquisar livros" as pesquisar_livros
usecase "UC14\nAplicar Filtros" as aplicar_filtros
usecase "UC15\nAcessar Estante" as acessar_estante

Leitor --> comprar_livros
UsuarioEditorial --> receber_por_livro

Leitor --> filtrar_livros
Leitor --> pesquisar_livros

pesquisar_livros ..> aplicar_filtros : <<extend>>
pesquisar_livros ..> acessar_estante : <<extend>>

comprar_livros ..> selecionar_metodo_pgto : <<include>>

' Feature - Leitura de Livros

usecase "UC16\nLer livros" as ler_livros
usecase "UC17\nMarcar página" as marcar_pagina
usecase "UC18\nFinalizar livro" as finalizar_livro

Leitor --> ler_livros

ler_livros ..> marcar_pagina : <<extend>>
ler_livros ..> finalizar_livro : <<extend>>

' Feature - Avaliação de Livros

usecase "UC19\nAvaliar livros" as avaliar_livros
usecase "UC20\nAdicionar comentário" as adicionar_comentario
usecase "UC21\nComentar em avaliações" as comentar_avaliacoes
usecase "UC22\nResponder avaliações de leitores" as responder_avaliacoes 

Leitor --> avaliar_livros
Leitor --> comentar_avaliacoes

UsuarioEditorial --> responder_avaliacoes

avaliar_livros ..> adicionar_comentario : <<extend>>

' Feature - Organização de Livros

actor "Subsistema de Bibliotecas" as SubsistemaBiblioteca

usecase "UC23\nCriar biblioteca" as criar_biblioteca
usecase "UC24\nInserir na estante de adquiridos" as inserir_estante_adquiridos
usecase "UC25\nInserir na estante de avaliados" as inserir_estante_avaliados
usecase "UC26\nInserir no histórico de livros" as inserir_historico_livros

SubsistemaBiblioteca --> criar_biblioteca
SubsistemaBiblioteca --> inserir_estante_adquiridos
SubsistemaBiblioteca --> inserir_estante_avaliados
SubsistemaBiblioteca --> inserir_historico_livros

usecase "UC27\nCriar nova estante" as criar_estante
usecase "UC28\nAdicionar à estante" as adicionar_livro_estante
usecase "UC29\nRemover da estante" as remover_livro_estante
usecase "UC30\nCriar sub-estante" as criar_sub_estante

Usuario --> criar_estante
Usuario --> adicionar_livro_estante
Usuario --> remover_livro_estante

criar_estante ..> criar_sub_estante : <<extend>>

' Feature - Dashboard Editorial

actor "Subsistema de Dashboard" as dashboard

usecase "UC31\nCalcular receita" as calcular_receita
usecase "UC32\nAnalisar perfil do público" as analisar_publico
usecase "UC33\nAnalisar avaliações" as analisar_avaliacoes 
usecase "UC34\nAnalisar livros" as analisar_livros
usecase "UC35\nAnalisar estantes" as analisar_estantes

dashboard --> calcular_receita
dashboard --> analisar_publico
dashboard --> analisar_avaliacoes
dashboard --> analisar_livros
dashboard --> analisar_estantes

@enduml