@startuml diagrama-de-classes

' Usuários e suas funções e permissões no sistema

abstract class Usuario {
    # nome: String
    # username: String
    # email: String
    # senha: String
    # Usuario(...)
    # login(email: String, senha: String) {abstract}
}

class Leitor {
    - livros: List<Livro>
    - estantes: List<Estante>
    - pontuacaoXP : PontuacaoXP
    - saldoMoedas : int
    - avaliacoes : List<Avaliacao>
    - cupons : List<Cupom>
    + comprarLivro(livro : Livro)
    + pegarLivro(livro: Livro)
    + aplicarCupom(cupom: Cupom)
    + removerCupom(cupom: Cupom)
    + lerLivro(livro: Livro)
}
Leitor --|> Usuario

abstract class UsuarioEditorial {
    # endereco : String
    # livros : List<Livro>
    # respostasAvaliacoes : List<ComentarioAvaliacao>
    # publicarLivro(livro: Livro) {abstract}
}
UsuarioEditorial --|> Usuario

class AutorIndependente {
    - cpf : String
    + publicarLivro(livro: Livro)
}
AutorIndependente --|> UsuarioEditorial

class Editora {
    - cnpj : String
    + publicarLivro(livro: Livro) 
}
Editora --|> UsuarioEditorial

' Livros, compras e empréstimos

class Livro {
    - isbn : String
    - titulo: String
    - autor: String
    - publicador: UsuarioEditorial
    - genero: EGenero
    - ano: int
    - preco: float
    - duracaoEmprestimo: int
    - dificuldade: int
    - sinopse: String
    - capa: String
    - arquivo: String
    - leitorArquivo: LeitorArquivo
    - cuponsAtivos: List<Cupom>
    + Livro(...)
    + aplicarCupom(cupom: Cupom)
    + removerCupom(cupom: Cupom)
    + precoFinal(): float
    + duracaoEmprestimo(): int
}
UsuarioEditorial "1" o-- "0..*" Livro : publica

@enduml