@startuml diagrama-classe
skinparam linetype ortho

abstract class Usuario {
    # nome: String
    # email: String
    # username: String
    # senha: String
    # biblioteca: Biblioteca
    # comentariosAvaliacao: List<ComentarioAvaliacao>
    + cadastrar(): void {abstract}
    + login(): void {abstract}
}

interface IComentador {
    + comentarAvaliacao(): void
    + editarComentario(): void
    + excluirComentario(): void
}

abstract class UsuarioEditorial {
    + cadastrarLivro(): void {abstract}
    + editarLivro(): void {abstract}
    + arquivarLivro(): void {abstract}
    + removerLivro(): void {abstract}
    + comentarAvaliacao() : void
    + editarComentario() : void
    + excluirComentario() : void
}
UsuarioEditorial --|> Usuario
UsuarioEditorial ..|> IComentador

class AutorIndependente {
    - cpf: String
}
AutorIndependente --|> UsuarioEditorial

class Editora {
    - cnpj: String
    - autoresLicenciados: List<String>
}
Editora --|> UsuarioEditorial

interface IAvaliador {
    + avaliarLivro(): void
    + editarAvaliacao(): void
    + excluirAvaliacao(): void
}

class Leitor {
    - avaliacoes: List<Avaliacao>
    + comprarLivro(): void
    + lerLivro(): void
}
Leitor --|> Usuario
Leitor ..|> IComentador
Leitor ..|> IAvaliador
@enduml