@startuml diagrama-pacotes
skinparam linetype ortho

package Model <<Layer>> {
    abstract class UsuarioEntity
    class LeitorEntity
    class AutorIndieEntity
    class EditoraEntity
    LeitorEntity --|> UsuarioEntity
    AutorIndieEntity --|> UsuarioEntity
    EditoraEntity --|> UsuarioEntity

    abstract class EstanteEntity
    class EstanteComumEntity
    class EstanteArquivadosEntity
    EstanteComumEntity --|> EstanteEntity
    EstanteArquivadosEntity --|> EstanteEntity

    class LivroEntity
    class LeitorEPUBEntity
    class PaginaEPUBEntity

    class AvaliacaoEntity
    class ComentarioAvaliacaoEntity
}
Model <-- Repository

package Enum {
    enum EGenero
}
Model "1" o-- "1..*" EGenero

package Repository <<Layer>> {
    class LeitorRepository
    class AutorIndieRepository
    class EditoraRepository
    class EstanteComumRepository
    class EstanteArquivadosRepository

    class LivroRepository
    class LeitorEPUBRepository
    class PaginaEPUBRepository

    class AvaliacaoRepository
    class ComentarioAvaliacaoRepository
}
Repository <-- DTO

package DTO {
    package Request {
        class AuthRequestDTO
        class LeitorRequestDTO
        class AutorIndieRequestDTO
        class EditoraRequestDTO
        class EstanteComumRequestDTO
        class EstanteArquivadosRequestDTO

        class LivroRequestDTO
        class LeitorEPUBRequestDTO
        class PaginaEPUBRequestDTO

        class AvaliacaoRequestDTO
        class ComentarioAvaliacaoRequestDTO
    }

    package Response {
        class AuthResponseDTO
        class LeitorResponseDTO
        class AutorIndieResponseDTO
        class EditoraResponseDTO
        class EstanteComumResponseDTO
        class EstanteArquivadosResponseDTO

        class LivroResponseDTO
        class LeitorEPUBResponseDTO
        class PaginaEPUBResponseDTO

        class AvaliacaoResponseDTO
        class ComentarioAvaliacaoResponseDTO
    }
}
DTO <-- Service

package Service <<Layer>> {
    class AuthService
    class LeitorService
    class AutorIndieService
    class EditoraService
    class EstanteComumService
    class EstanteArquivadosService

    class LivroService
    class LeitorEPUBService
    class PaginaEPUBService

    class AvaliacaoService
    class ComentarioAvaliacaoService

    class DashboardService
}
Service <-- Controller

package Controller <<Layer>> {
    class AuthController
    class LeitorController
    class AutorIndieController
    class EditoraController
    class EstanteComumController
    class EstanteArquivadosController

    class LivroController
    class LeitorEPUBController
    class PaginaEPUBController

    class AvaliacaoController
    class ComentarioAvaliacaoController

    class DashboardController
}

package Exception {
    class CredenciaisInvalidasException
    class PerfilLoginInvalidoException
    class LivroIndisponivelException
    class EstanteIndisponivelException
    class MetodoPgtoInvalidoException
    class CompraCanceladaException
    class AvaliacaoNaoEncontradaException
    class ComentarioNaoEncontradoException
}
Service "1..*" o-- "0..*" Exception
Controller "1..*" o-- "0..*" Exception

@enduml