@startuml dc-inserir_estante_avaliados
autonumber
skinparam style strictuml

participant Sistema           as "Subsistema de Bibliotecas"
participant ServiceBiblioteca as "Serviço de Biblioteca"
database    BD                as "Banco de Dados"

[-> Sistema : evento: avaliação publicada\n(leitorId, livroId)

Sistema -> ServiceBiblioteca : GET /bibliotecas/acervos\n(leitorId, nome="Avaliados")
ServiceBiblioteca -> BD : SELECT acervo WHERE\nbibliotecaId IN (SELECT id FROM biblioteca\nWHERE usuarioId = {leitorId})\nAND nome = "Avaliados"
BD --> ServiceBiblioteca : acervoId
ServiceBiblioteca --> Sistema : acervoId

Sistema -> ServiceBiblioteca : GET /acervos/{acervoId}/livros/{livroId}
ServiceBiblioteca -> BD : SELECT estante_livro WHERE\nacervoId = {id} AND livroId = {id}
BD --> ServiceBiblioteca : resultado (presente ou ausente)
ServiceBiblioteca --> Sistema : resultado

Sistema -> ServiceBiblioteca : POST /acervos/{acervoId}/livros(livroId)
ServiceBiblioteca -> BD : INSERT estante_livro\n(acervoId, livroId)
BD --> ServiceBiblioteca : livro inserido
ServiceBiblioteca --> Sistema : 201 Created
Sistema -> Sistema : nenhuma ação necessária

@enduml
